version: 0.0
os: linux
files:
-source: /pom.xml
destination: /usr/tmp/mywebapp_new
-source: target/ROOT.war
destination: /var/lib/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root   
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
