version: 0.0
os: linux
files:
-source: /
destination: /opt/codedeploy-agent/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root   
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
