version: 0.0
os: linux
files:
-source: /deployment-root
destination: /usr/local/mywebapp
permissions:
    -object: /deployment-root
    pattern: "**"
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root   
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
