version: 0.0
os: linux
files:
-source: /opt/codedeploy-agent/deployment-root
destination: /usr/local/mywebapp
permissions:
-object: /opt/codedeploy-agent/deployment-root
pattern: "**"
owner: ec2-user
mode: 777
type: -directory
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root   
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
