version: 0.0
os: linux
files:
-source: target/ROOT.war
destination: /usr/local/mywebapp
permissions:
-object: target/ROOT.war
pattern: "**"
type: -file
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root   
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
