version: 0.0
os: linux
files:
-source: ./Dockerfile
destination: ./opt/codedeploy-agent/
-source: target/ROOT.war
destination: /var/lib/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root   
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
