version: 0.0
os: linux
files:
-source: target
destination: /usr/local/mywebapp
permissions:
    -object: /target
    pattern: "**"
    type: -directory
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root   
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
