branch-defaults:
  master:
    environment: eb-qa
global:
  application_name: MyWebApplication
  default_ec2_keyname: aws_demo
  default_platform: 64bit Amazon Linux 2015.03 v2.0.2 running Docker 1.7.1
  default_region: us-west-2
  profile: null
  sc: git
